spring:
  application:
    name: Gamegiaido
  profiles:
    active: mysql
  datasource:
    url: jdbc:h2:mem:gamegiaido
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: false
      path: /h2-console
  mail:
    host: smtp.gmail.com
    port: 587
    username: minhthe0359898246@gmail.com
    password: fkcv ujoi wtax qrua
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
