CREATE TABLE IF NOT EXISTS user_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_user_accounts_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS player_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    display_name VARCHAR(80) NOT NULL,
    total_score INT NOT NULL,
    reward_points INT NOT NULL DEFAULT 0,
    reward_wallet_initialized BOOLEAN NOT NULL DEFAULT FALSE,
    selected_character_icon VARCHAR(40) NOT NULL DEFAULT 'agent_default',
    owned_character_icons VARCHAR(600) NOT NULL DEFAULT 'agent_default',
    total_win INT NOT NULL,
    avatar_url VARCHAR(500) NULL,
    account_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_player_profiles_account_id UNIQUE (account_id),
    CONSTRAINT fk_player_profiles_account FOREIGN KEY (account_id) REFERENCES user_accounts(id)
);

ALTER TABLE player_profiles
    ADD COLUMN IF NOT EXISTS reward_points INT NOT NULL DEFAULT 0;

ALTER TABLE player_profiles
    ADD COLUMN IF NOT EXISTS reward_wallet_initialized BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE player_profiles
    ADD COLUMN IF NOT EXISTS selected_character_icon VARCHAR(40) NOT NULL DEFAULT 'agent_default';

ALTER TABLE player_profiles
    ADD COLUMN IF NOT EXISTS owned_character_icons VARCHAR(600) NOT NULL DEFAULT 'agent_default';

CREATE TABLE IF NOT EXISTS quiz_topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_quiz_topics_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS game_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(255) NOT NULL,
    room_order INT NOT NULL,
    mode VARCHAR(30) NOT NULL,
    topic_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_game_rooms_topic FOREIGN KEY (topic_id) REFERENCES quiz_topics(id)
);

CREATE TABLE IF NOT EXISTS room_objects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    object_name VARCHAR(120) NOT NULL,
    hint VARCHAR(255) NOT NULL,
    hotspot_x INT NULL,
    hotspot_y INT NULL,
    locked BOOLEAN NOT NULL,
    required_step INT NOT NULL,
    lock_type VARCHAR(20) NOT NULL,
    room_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_room_objects_room FOREIGN KEY (room_id) REFERENCES game_rooms(id)
);

CREATE TABLE IF NOT EXISTS room_key_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    room_id BIGINT NOT NULL,
    key_code VARCHAR(80) NOT NULL,
    key_name VARCHAR(120) NOT NULL,
    image_url VARCHAR(500) NULL,
    spot_x INT NOT NULL,
    spot_y INT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_room_key_configs_room FOREIGN KEY (room_id) REFERENCES game_rooms(id)
);

CREATE TABLE IF NOT EXISTS quiz_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    room_object_id BIGINT NOT NULL,
    question_text VARCHAR(255) NOT NULL,
    clue_text VARCHAR(255) NULL,
    answer_code VARCHAR(40) NULL,
    optiona VARCHAR(255) NOT NULL,
    optionb VARCHAR(255) NOT NULL,
    optionc VARCHAR(255) NOT NULL,
    optiond VARCHAR(255) NOT NULL,
    correct_option VARCHAR(1) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_quiz_questions_room_object_id UNIQUE (room_object_id),
    CONSTRAINT fk_quiz_questions_room_object FOREIGN KEY (room_object_id) REFERENCES room_objects(id)
);

CREATE TABLE IF NOT EXISTS player_room_progresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    player_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    current_step INT NOT NULL,
    completed BOOLEAN NOT NULL,
    score INT NOT NULL,
    wrong_attempts INT NOT NULL,
    won BOOLEAN NULL,
    result_finalized BOOLEAN NOT NULL,
    collected_items VARCHAR(600) NOT NULL,
    discovered_clues VARCHAR(1200) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_player_room UNIQUE (player_id, room_id),
    CONSTRAINT fk_player_room_progresses_player FOREIGN KEY (player_id) REFERENCES player_profiles(id),
    CONSTRAINT fk_player_room_progresses_room FOREIGN KEY (room_id) REFERENCES game_rooms(id)
);

CREATE TABLE IF NOT EXISTS play_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    player_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    score INT NOT NULL,
    result VARCHAR(10) NOT NULL,
    action_count INT NOT NULL DEFAULT 0,
    played_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_play_histories_player FOREIGN KEY (player_id) REFERENCES player_profiles(id),
    CONSTRAINT fk_play_histories_room FOREIGN KEY (room_id) REFERENCES game_rooms(id)
);

CREATE TABLE IF NOT EXISTS reward_vouchers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(60) NOT NULL,
    name VARCHAR(140) NOT NULL,
    brand VARCHAR(80) NOT NULL,
    points_cost INT NOT NULL,
    total_stock INT NOT NULL,
    remaining_stock INT NOT NULL,
    expires_at DATE NOT NULL,
    active BOOLEAN NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_reward_vouchers_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS voucher_redemptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    player_id BIGINT NOT NULL,
    voucher_id BIGINT NOT NULL,
    points_spent INT NOT NULL,
    issued_code VARCHAR(100) NOT NULL,
    redeemed_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_voucher_redemptions_issued_code UNIQUE (issued_code),
    CONSTRAINT uk_voucher_redeem_player_voucher UNIQUE (player_id, voucher_id),
    CONSTRAINT fk_voucher_redemptions_player FOREIGN KEY (player_id) REFERENCES player_profiles(id),
    CONSTRAINT fk_voucher_redemptions_voucher FOREIGN KEY (voucher_id) REFERENCES reward_vouchers(id)
);

ALTER TABLE voucher_redemptions
    ADD COLUMN IF NOT EXISTS issued_code VARCHAR(100) NOT NULL DEFAULT 'PENDING-CODE';
