CREATE TABLE IF NOT EXISTS user_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_user_accounts_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS player_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    display_name VARCHAR(80) NOT NULL,
    total_score INT NOT NULL,
    total_win INT NOT NULL,
    avatar_url VARCHAR(500) NULL,
    account_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_player_profiles_account_id UNIQUE (account_id),
    CONSTRAINT fk_player_profiles_account FOREIGN KEY (account_id) REFERENCES user_accounts(id)
);

CREATE TABLE IF NOT EXISTS quiz_topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_quiz_topics_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS game_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(255) NOT NULL,
    room_order INT NOT NULL,
    mode VARCHAR(30) NOT NULL,
    topic_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_game_rooms_topic FOREIGN KEY (topic_id) REFERENCES quiz_topics(id)
);

CREATE TABLE IF NOT EXISTS room_objects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    object_name VARCHAR(120) NOT NULL,
    hint VARCHAR(255) NOT NULL,
    hotspot_x INT NULL,
    hotspot_y INT NULL,
    locked BOOLEAN NOT NULL,
    required_step INT NOT NULL,
    lock_type VARCHAR(20) NOT NULL,
    room_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_room_objects_room FOREIGN KEY (room_id) REFERENCES game_rooms(id)
);

CREATE TABLE IF NOT EXISTS room_key_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    room_id BIGINT NOT NULL,
    key_code VARCHAR(80) NOT NULL,
    key_name VARCHAR(120) NOT NULL,
    image_url VARCHAR(500) NULL,
    spot_x INT NOT NULL,
    spot_y INT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_room_key_configs_room FOREIGN KEY (room_id) REFERENCES game_rooms(id)
);

CREATE TABLE IF NOT EXISTS quiz_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    room_object_id BIGINT NOT NULL,
    question_text VARCHAR(255) NOT NULL,
    clue_text VARCHAR(255) NULL,
    answer_code VARCHAR(40) NULL,
    optiona VARCHAR(255) NOT NULL,
    optionb VARCHAR(255) NOT NULL,
    optionc VARCHAR(255) NOT NULL,
    optiond VARCHAR(255) NOT NULL,
    correct_option VARCHAR(1) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_quiz_questions_room_object_id UNIQUE (room_object_id),
    CONSTRAINT fk_quiz_questions_room_object FOREIGN KEY (room_object_id) REFERENCES room_objects(id)
);

CREATE TABLE IF NOT EXISTS player_room_progresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    player_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    current_step INT NOT NULL,
    completed BOOLEAN NOT NULL,
    score INT NOT NULL,
    wrong_attempts INT NOT NULL,
    won BOOLEAN NULL,
    result_finalized BOOLEAN NOT NULL,
    collected_items VARCHAR(600) NOT NULL,
    discovered_clues VARCHAR(1200) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_player_room UNIQUE (player_id, room_id),
    CONSTRAINT fk_player_room_progresses_player FOREIGN KEY (player_id) REFERENCES player_profiles(id),
    CONSTRAINT fk_player_room_progresses_room FOREIGN KEY (room_id) REFERENCES game_rooms(id)
);

CREATE TABLE IF NOT EXISTS play_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    player_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    score INT NOT NULL,
    result VARCHAR(10) NOT NULL,
    action_count INT NOT NULL DEFAULT 0,
    played_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_play_histories_player FOREIGN KEY (player_id) REFERENCES player_profiles(id),
    CONSTRAINT fk_play_histories_room FOREIGN KEY (room_id) REFERENCES game_rooms(id)
);
