package com.example.gamegiaido.config;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import javax.sql.DataSource;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
@Order(0)
public class RoomObjectSchemaUpdater implements CommandLineRunner {

    private final DataSource dataSource;
    private final JdbcTemplate jdbcTemplate;

    public RoomObjectSchemaUpdater(DataSource dataSource, JdbcTemplate jdbcTemplate) {
        this.dataSource = dataSource;
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void run(String... args) throws Exception {
        jdbcTemplate.execute(getCreateRoomKeyConfigsSql());

        Set<String> columns = getRoomObjectColumns();

        if (!columns.contains("hotspot_x")) {
            jdbcTemplate.execute("ALTER TABLE room_objects ADD COLUMN hotspot_x INT NULL");
        }

        if (!columns.contains("hotspot_y")) {
            jdbcTemplate.execute("ALTER TABLE room_objects ADD COLUMN hotspot_y INT NULL");
        }

        Set<String> progressColumns = getColumns("player_room_progresses");
        if (!progressColumns.contains("collected_items")) {
            jdbcTemplate.execute("ALTER TABLE player_room_progresses ADD COLUMN collected_items VARCHAR(600) NOT NULL DEFAULT ''");
        }
        if (!progressColumns.contains("discovered_clues")) {
            jdbcTemplate.execute("ALTER TABLE player_room_progresses ADD COLUMN discovered_clues VARCHAR(1200) NOT NULL DEFAULT ''");
        }

        Set<String> profileColumns = getColumns("player_profiles");
        if (!profileColumns.contains("avatar_url")) {
            jdbcTemplate.execute("ALTER TABLE player_profiles ADD COLUMN avatar_url VARCHAR(500) NULL");
        }

        Set<String> playHistoryColumns = getColumns("play_histories");
        if (!playHistoryColumns.contains("action_count")) {
            jdbcTemplate.execute("ALTER TABLE play_histories ADD COLUMN action_count INT NOT NULL DEFAULT 0");
        }

        Set<String> questionColumns = getColumns("quiz_questions");
        if (!questionColumns.contains("clue_text")) {
            jdbcTemplate.execute("ALTER TABLE quiz_questions ADD COLUMN clue_text VARCHAR(255) NULL");
        }
        if (!questionColumns.contains("answer_code")) {
            jdbcTemplate.execute("ALTER TABLE quiz_questions ADD COLUMN answer_code VARCHAR(40) NULL");
        }

        seedScenarioIfEmpty();
    }

    private String getCreateRoomKeyConfigsSql() throws SQLException {
        try (Connection connection = dataSource.getConnection()) {
            String databaseProductName = connection.getMetaData().getDatabaseProductName().toLowerCase(Locale.ROOT);
            if (databaseProductName.contains("postgresql")) {
                return """
                        CREATE TABLE IF NOT EXISTS room_key_configs (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                            room_id BIGINT NOT NULL,
                            key_code VARCHAR(80) NOT NULL,
                            key_name VARCHAR(120) NOT NULL,
                            image_url VARCHAR(500) NULL,
                            spot_x INT NOT NULL,
                            spot_y INT NOT NULL,
                            PRIMARY KEY (id),
                            CONSTRAINT fk_room_key_configs_room FOREIGN KEY (room_id) REFERENCES game_rooms(id)
                        )
                        """;
            }
        }

        return """
                CREATE TABLE IF NOT EXISTS room_key_configs (
                    id BIGINT NOT NULL AUTO_INCREMENT,
                    room_id BIGINT NOT NULL,
                    key_code VARCHAR(80) NOT NULL,
                    key_name VARCHAR(120) NOT NULL,
                    image_url VARCHAR(500) NULL,
                    spot_x INT NOT NULL,
                    spot_y INT NOT NULL,
                    PRIMARY KEY (id),
                    CONSTRAINT fk_room_key_configs_room FOREIGN KEY (room_id) REFERENCES game_rooms(id)
                )
                """;
    }

    private Set<String> getRoomObjectColumns() throws SQLException {
        return getColumns("room_objects");
    }

    private Set<String> getColumns(String tableName) throws SQLException {
        Set<String> columns = new HashSet<>();
        try (Connection connection = dataSource.getConnection()) {
            DatabaseMetaData metaData = connection.getMetaData();
            try (ResultSet rs = metaData.getColumns(connection.getCatalog(), null, tableName, null)) {
                while (rs.next()) {
                    columns.add(rs.getString("COLUMN_NAME").toLowerCase(Locale.ROOT));
                }
            }
            if (!columns.isEmpty()) {
                return columns;
            }
            try (ResultSet rs = metaData.getColumns(connection.getCatalog(), null, tableName.toUpperCase(Locale.ROOT), null)) {
                while (rs.next()) {
                    columns.add(rs.getString("COLUMN_NAME").toLowerCase(Locale.ROOT));
                }
            }
        }
        return columns;
    }

    private void seedScenarioIfEmpty() {
        Long roomCount = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM game_rooms", Long.class);
        if (roomCount != null && roomCount > 0) {
            return;
        }

        jdbcTemplate.update("INSERT INTO quiz_topics (name, description) VALUES ('Kịch bản', 'Thí Nghiệm Bị Ngắt Quãng')");

        Long topicId = jdbcTemplate.queryForObject(
                "SELECT id FROM quiz_topics WHERE name = 'Kịch bản' LIMIT 1",
                Long.class
        );

        if (topicId == null) {
            throw new IllegalStateException("Không thể tạo chủ đề kịch bản.");
        }

        seedInterruptedExperimentRoom(topicId);
        seedNightCipherRoom(topicId);
        seedAncientVaultRoom(topicId);
        seedVictorianStudyRoom(topicId);
    }

        private void seedInterruptedExperimentRoom(Long topicId) {
        Long roomId = insertRoom(
            topicId,
            "Thí Nghiệm Bị Ngắt Quãng",
            "Thu thập vật phẩm, giải mã tủ, kích hoạt máy quét và thoát bằng keycard.",
            1
        );

        insertRoomObject(roomId, "Tủ gỗ khóa mã 3 số", "Dùng bút chì tô giấy trắng để lộ mã", 68, 33, 1, "QUIZ");
        insertRoomObject(roomId, "Kính hiển vi", "Lắp ống kính và mẫu vật để soi", 40, 38, 2, "INTERACTION");
        insertRoomObject(roomId, "Máy quét cạnh cửa", "Đổ dung dịch tím vào phễu để kích hoạt", 78, 45, 3, "INTERACTION");
        insertRoomObject(roomId, "Bảng nhập hình dạng vi khuẩn", "Nhập hình dạng quan sát được từ kính hiển vi", 82, 28, 4, "QUIZ");

        Long cabinetId = getObjectId(roomId, "Tủ gỗ khóa mã 3 số");
        Long finalConsoleId = getObjectId(roomId, "Bảng nhập hình dạng vi khuẩn");
        insertQuizQuestion(
            cabinetId,
            "Nhập mã 3 chữ số để mở tủ gỗ",
            "Mã xuất hiện khi tô bút chì lên tờ giấy trắng",
            "741",
            "---",
            "---",
            "---",
            "---",
            "A"
        );
        insertQuizQuestion(
            finalConsoleId,
            "Hình dạng vi khuẩn bạn nhìn thấy là gì?",
            "Gợi ý nằm trong kính hiển vi",
            null,
            "Hình Tròn",
            "Hình Tam Giác",
            "Hình Vuông",
            "Hình Lục Giác",
            "B"
        );

        insertKeySpot(roomId, "lens", "Ống kính", 22, 55);
        insertKeySpot(roomId, "pencil", "Bút chì", 78, 22);
        insertKeySpot(roomId, "white_paper", "Tờ giấy trắng", 48, 56);
        insertKeySpot(roomId, "glass_cup", "Cốc thủy tinh", 18, 28);
        insertKeySpot(roomId, "yellow_powder", "Lọ bột màu vàng", 12, 67);
        }

        private void seedNightCipherRoom(Long topicId) {
        Long roomId = insertRoom(
            topicId,
            "Mật Mã Bóng Đêm",
            "Tìm manh mối UV, giải bảng mã và mở cổng thoát bí mật.",
            2
        );

        insertRoomObject(roomId, "Bảng mã UV", "Rọi đèn UV lên mảnh bản đồ để thấy dãy số", 64, 32, 1, "QUIZ");
        insertRoomObject(roomId, "Bệ giải mã trung tâm", "Lắp vòng giải mã đúng vị trí", 45, 48, 2, "INTERACTION");
        insertRoomObject(roomId, "Bảng xác thực cuối", "Chọn ký hiệu khớp với chuỗi ánh tím", 80, 30, 3, "QUIZ");

        Long uvBoardId = getObjectId(roomId, "Bảng mã UV");
        Long finalPanelId = getObjectId(roomId, "Bảng xác thực cuối");
        insertQuizQuestion(
            uvBoardId,
            "Nhập mã 3 chữ số vừa hiện dưới đèn UV",
            "Mã nằm ở góc phải mảnh bản đồ",
            "586",
            "---",
            "---",
            "---",
            "---",
            "A"
        );
        insertQuizQuestion(
            finalPanelId,
            "Ký hiệu nào khớp với chuỗi ánh tím sau khi xoay vòng mã?",
            "Quan sát thứ tự ký hiệu trên vòng giải mã",
            null,
            "Ký hiệu Mặt Trăng",
            "Ký hiệu Mũi Tên",
            "Ký hiệu Con Mắt",
            "Ký hiệu Sóng Nước",
            "C"
        );

        insertKeySpot(roomId, "map_fragment", "Mảnh bản đồ", 28, 52);
        insertKeySpot(roomId, "uv_lamp", "Đèn UV", 73, 30);
        insertKeySpot(roomId, "cipher_ring", "Vòng giải mã", 51, 64);
        insertKeySpot(roomId, "moon_shard", "Mảnh trăng vỡ", 18, 36);
        insertKeySpot(roomId, "shadow_ink", "Mực bóng đêm", 62, 70);
        insertKeySpot(roomId, "star_compass", "La bàn sao", 84, 56);
        }

        private void seedAncientVaultRoom(Long topicId) {
        Long roomId = insertRoom(
            topicId,
            "Kho Cổ Vật Thức Tỉnh",
            "Giải ký tự cổ, kích hoạt tượng canh và mở ấn phong cuối cùng.",
            3
        );

        insertRoomObject(roomId, "Bệ đá ký tự cổ", "Dùng than đồ nét để hiện mã khắc", 30, 36, 1, "QUIZ");
        insertRoomObject(roomId, "Tượng canh gác", "Đặt phiến đá đúng hốc để mở khóa cơ", 52, 52, 2, "INTERACTION");
        insertRoomObject(roomId, "Cổng niêm phong", "Dùng chìa đồng để hoàn tất nghi thức mở cổng", 82, 38, 3, "INTERACTION");

        Long stonePedestalId = getObjectId(roomId, "Bệ đá ký tự cổ");
        insertQuizQuestion(
            stonePedestalId,
            "Nhập mã 3 chữ số khắc trên bệ đá",
            "Mã xuất hiện rõ khi đồ than lên phiến ký tự",
            "314",
            "---",
            "---",
            "---",
            "---",
            "A"
        );

        insertKeySpot(roomId, "stone_tablet", "Phiến đá cổ", 66, 44);
        insertKeySpot(roomId, "charcoal", "Than đồ nét", 22, 61);
        insertKeySpot(roomId, "bronze_key", "Chìa đồng", 48, 25);
        insertKeySpot(roomId, "relic_coin", "Đồng xu cổ", 34, 42);
        insertKeySpot(roomId, "scarab_token", "Bùa bọ hung", 78, 64);
        insertKeySpot(roomId, "obsidian_fragment", "Mảnh hắc thạch", 12, 48);
    }

    private void seedVictorianStudyRoom(Long topicId) {
        Long roomId = insertRoom(
            topicId,
            "Phòng Nghiên Cứu Victorian",
            "Khám phá phòng làm việc của học giả biến mất, giải mã bí ẩn và thoát ra.",
            4
        );

        // Step 1: Thu thập 3 manh mối từ cửa sổ, bàn làm việc, và dưới thảm
        insertRoomObject(roomId, "Cửa sổ Victoria", "Ánh sáng qua cửa sổ tạo shadow pattern trên sàn", 25, 45, 1, "INTERACTION");
        insertRoomObject(roomId, "Bàn làm việc", "Nhật ký cũ trên bàn chứa cipher code", 50, 55, 1, "INTERACTION");
        insertRoomObject(roomId, "Thảm Ba Tư", "Nhấc thảm lên để tìm manh mối bí mật", 65, 60, 1, "INTERACTION");

        // Step 2: Mở tủ sách bằng mã 3 số
        insertRoomObject(roomId, "Tủ sách khóa mã", "Nhập mã 3 chữ số từ các manh mối đã thu thập", 15, 50, 2, "QUIZ");

        // Step 3: Sử dụng máy tiện với blueprint
        insertRoomObject(roomId, "Máy tiện cổ", "Sử dụng blueprint và vật liệu để tạo chìa khóa", 80, 40, 3, "INTERACTION");

        // Step 4: Thoát phòng
        insertRoomObject(roomId, "Cửa thoát hiểm", "Dùng chìa khóa vừa tạo để mở cửa", 50, 20, 4, "INTERACTION");

        // Quiz cho tủ sách
        Long cabinetId = getObjectId(roomId, "Tủ sách khóa mã");
        insertQuizQuestion(
            cabinetId,
            "Nhập mã 3 chữ số từ các manh mối trong phòng",
            "Cửa sổ (3), Nhật ký (9), Dưới thảm (7)",
            "397",
            "---",
            "---",
            "---",
            "---",
            "A"
        );

        // Các vật phẩm có thể nhặt
        insertKeySpot(roomId, "window_clue", "Manh mối cửa sổ (số 3)", 26, 48);
        insertKeySpot(roomId, "diary_clue", "Manh mối nhật ký (số 9)", 51, 57);
        insertKeySpot(roomId, "carpet_clue", "Manh mối thảm (số 7)", 66, 62);
        insertKeySpot(roomId, "blueprint", "Bản thiết kế máy tiện", 16, 52);
        insertKeySpot(roomId, "metal_rod", "Thanh kim loại", 35, 65);
        insertKeySpot(roomId, "polish_oil", "Dầu đánh bóng", 70, 35);
        insertKeySpot(roomId, "clock_key", "Chìa đồng hồ", 58, 30);
        insertKeySpot(roomId, "wax_seal", "Con dấu sáp", 82, 55);
    }

        private Long insertRoom(Long topicId, String name, String description, int order) {
        jdbcTemplate.update(
            "INSERT INTO game_rooms (name, description, room_order, mode, topic_id) VALUES (?, ?, ?, ?, ?)",
            name,
            description,
            order,
            "QUIZ_ESCAPE_ROOM",
            topicId
        );

        Long roomId = jdbcTemplate.queryForObject(
            "SELECT id FROM game_rooms WHERE name = ? LIMIT 1",
            Long.class,
            name
        );
        if (roomId == null) {
            throw new IllegalStateException("Không thể tạo phòng kịch bản: " + name);
        }
        return roomId;
        }

        private void insertRoomObject(Long roomId,
                      String objectName,
                      String hint,
                      int hotspotX,
                      int hotspotY,
                      int requiredStep,
                      String lockType) {
        jdbcTemplate.update(
            "INSERT INTO room_objects (object_name, hint, hotspot_x, hotspot_y, locked, required_step, lock_type, room_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
            objectName,
            hint,
            hotspotX,
            hotspotY,
            true,
            requiredStep,
            lockType,
            roomId
        );
        }

        private Long getObjectId(Long roomId, String objectName) {
        Long objectId = jdbcTemplate.queryForObject(
            "SELECT id FROM room_objects WHERE room_id = ? AND object_name = ? LIMIT 1",
            Long.class,
            roomId,
            objectName
        );
        if (objectId == null) {
            throw new IllegalStateException("Không thể tạo vật thể kịch bản: " + objectName);
        }
        return objectId;
        }

        private void insertQuizQuestion(Long roomObjectId,
                        String questionText,
                        String clueText,
                        String answerCode,
                        String optionA,
                        String optionB,
                        String optionC,
                        String optionD,
                        String correctOption) {
        jdbcTemplate.update(
            "INSERT INTO quiz_questions (room_object_id, question_text, clue_text, answer_code, optiona, optionb, optionc, optiond, correct_option) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
            roomObjectId,
            questionText,
            clueText,
            answerCode,
            optionA,
            optionB,
            optionC,
            optionD,
            correctOption
        );
        }

        private void insertKeySpot(Long roomId, String keyCode, String keyName, int x, int y) {
        String imageUrl = switch (keyCode) {
            case "lens" -> "/images/items/lens.svg";
            case "pencil" -> "/images/items/pencil.svg";
            case "white_paper" -> "/images/items/white-paper.svg";
            case "glass_cup" -> "/images/items/glass-cup.svg";
            case "yellow_powder" -> "/images/items/yellow-powder.svg";
            // Night Cipher Room items
            case "map_fragment" -> "/images/items/map-fragment.svg";
            case "uv_lamp" -> "/images/items/uv-lamp.svg";
            case "cipher_ring" -> "/images/items/cipher-ring.svg";
            case "moon_shard" -> "/images/items/moon-shard.svg";
            case "shadow_ink" -> "/images/items/shadow-ink.svg";
            case "star_compass" -> "/images/items/star-compass.svg";
            // Ancient Vault Room items
            case "stone_tablet" -> "/images/items/stone-tablet.svg";
            case "charcoal" -> "/images/items/charcoal.svg";
            case "bronze_key" -> "/images/items/bronze-key.svg";
            case "relic_coin" -> "/images/items/relic-coin.svg";
            case "scarab_token" -> "/images/items/scarab-token.svg";
            case "obsidian_fragment" -> "/images/items/obsidian-fragment.svg";
            // Victorian Study Room items
            case "window_clue" -> "/images/items/window-clue.svg";
            case "diary_clue" -> "/images/items/diary-clue.svg";
            case "carpet_clue" -> "/images/items/carpet-clue.svg";
            case "blueprint" -> "/images/items/blueprint.svg";
            case "metal_rod" -> "/images/items/metal-rod.svg";
            case "polish_oil" -> "/images/items/polish-oil.svg";
            case "clock_key" -> "/images/items/clock-key.svg";
            case "wax_seal" -> "/images/items/wax-seal.svg";
            default -> null;
        };
        jdbcTemplate.update(
                "INSERT INTO room_key_configs (room_id, key_code, key_name, image_url, spot_x, spot_y) VALUES (?, ?, ?, ?, ?, ?)",
                roomId,
                keyCode,
                keyName,
                imageUrl,
                x,
                y
        );
    }
}
